### ISSUE TITLE
API 建议：允许被 hook 的应用获知自己哪些地方被 hook 及模块信息

### ISSUE THREAD

**Issue by drakeet** [libxposed/api#1]
如题，这是一个应用向的 API，如此一来就可以避免一些应用对于 Xposed hook 行为一棍子打死的做法。

也就是说，通过 API，被 hook 的应用可以获取到对其起作用的 Xposed 模块所有必要信息，这样只要不涉及核心业务或破解，那即使进程里发现 LSP 的踪影，也可以允许无害模块继续工作和 hook。

**Comment by Dr-TSNG** [comment]
这没有什么意义，如果一个东西可能被滥用，那么它就一定会被滥用。至少各种安全 SDK 一定会直接一棒子打死。

**Comment by canyie** [comment]
恶意的框架可以直接篡改这个 API 的响应，所以没有意义。

**Comment by drakeet** [comment]
现在就是一棍子打死，包括不是恶意的模块。如果 LSP 框架能够进行可靠性保证，还是很有意义的。

**Comment by vvb2060** [comment]
因为我们是开源的，所以无法做出任何保证。
