### ISSUE TITLE
可以将代码里的  hooker 改名为 hook 吗

### ISSUE THREAD

**Issue by SoClear** [libxposed/api#11]
代码里有很多 “hooker”，见：[代码里有很多 “hooker”](https://github.com/search?q=repo%3Alibxposed%2Fapi%20hooker&type=code)

可是 hooker 只有妓女的意思，见 [hooker翻译](https://dictionary.cambridge.org/dictionary/english-chinese-simplified/hooker)

hook 本身就有名词钩子的意思，见 [hook翻译](https://dictionary.cambridge.org/dictionary/english-chinese-simplified/hook)

能不能把代码里的  hooker 都改为 hook ？

**Comment by vvb2060** [comment]
是不是还要将master换成main？
