### ISSUE TITLE
Allow Hooks in the java.net Package

### ISSUE THREAD

**Issue by DavidBerdik** [libxposed/api#19]
I am writing a new module that requires hooking a function in `java.net.NetworkInterface`, but it seems that I am unable to do so.

I do not receive any error when I try to apply the hook, but when the function is executed, the hook does not execute. It is also worth noting that it seems that I am able to enter an incorrect name for a method and it will still not throw an error.

If further information is needed about the nature of the problem I am facing, please let me know and I will be happy to provide it.

**Comment by yujincheng08** [comment]
https://github.com/LSPosed/LSPosed

**Comment by DavidBerdik** [comment]
Should I post the issue under Discussions?

**Comment by DavidBerdik** [comment]
I have attempted to post about the issue under the Discussions tab at https://github.com/LSPosed/LSPosed, but I do not have the privileges to do so.

@yujincheng08 or someone else on the team: Please advise on how I can address this.

**Comment by DavidBerdik** [comment]
After further investigation, I have determined that this issue is not present in the old API.
