### ISSUE TITLE
Please provide invoke-special or CallNonVirutualXXXMethod() like API

### ISSUE THREAD

**Issue by superguo** [libxposed/api#2]
Sometimes we need to call the super class' method for the hooking method, and currently we can only do that by introducing a native .so library and dynamatically load it and call CallNonvirtualXXXMethod(). So if would be very nice if there is such an LSPosed API.
You can talk to me in Chinese in private anyway.

**Comment by yujincheng08** [comment]
Any example modules? We need to verify and determine the interface.

**Comment by superguo** [comment]
I will make one later.

**Comment by yujincheng08** [comment]
Please see if this meets your requirement:
https://github.com/LSPosed/LSPosed/commit/0b60b2054ac379139d234bdf8cce99c63443a1b7

**Comment by superguo** [comment]
> Please see if this meets your requirement: [LSPosed/LSPosed@c50bc2d](https://github.com/LSPosed/LSPosed/commit/c50bc2d1cf81145cf762acba2e4a20493d6d5612)

Yes, that's exactly what I need. Thank you so much.
