### ISSUE TITLE
Class io.github.libxposed.api.annotations does not exist

### ISSUE THREAD

**Issue by solely** [libxposed/api#23]
In the example project https://github.com/libxposed/example/blob/master/app/src/main/java/io/github/libxposed/example/ModuleMain.kt
the class io.github.libxposed.api.annotations is introduced, but not in the source code.

在 example项目中 https://github.com/libxposed/example/blob/master/app/src/main/java/io/github/libxposed/example/ModuleMain.kt
有引入 io.github.libxposed.api.annotations 这个类，源码里却没有。

**Comment by vvb2060** [comment]
明明是无法在公开版LSPosed上加载的问题更大吧

**Comment by solely** [comment]
嗯你说的对，我编译成aar使用时发现了。

**Comment by vvb2060** [comment]
https://github.com/libxposed/api/commit/7b6727313cb4864618d3c5b9dcdfb9f4f9bb378a

**Comment by solely** [comment]
三克油，我是将api、service、helper三个项目集成到自己的测试项目中才发现注解类不存在的。
