### ISSUE TITLE
Set\get Object extra

### ISSUE THREAD

**Issue by neervanbiqs** [libxposed/api#27]
In legacy xposed api there are methods setObjectExtra and getObjectExtra inside XC_MethodHook.MethodHookParam class. Also in XposedHelpers class there are methods setAdditionalStaticField and пetAdditionalStaticField
My module uses these methods. Is there an alternative in new api?

**Comment by vvb2060** [comment]
https://github.com/libxposed/api/blob/ca2e4b8da8b21a60578f290278fbfe5d1e3e3c07/api/src/main/java/io/github/libxposed/api/XposedInterface.java#L180

**Comment by neervanbiqs** [comment]
Thx!
Your answer is about extra object between before and after invocations. Well. But what about legacy setAdditionalStaticField and getAdditionalStaticField? For example I need to set extra field to param.thisObject in some hooked method and get this extra in another hooked method?

**Comment by vvb2060** [comment]
static kv map

**Comment by neervanbiqs** [comment]
Got it. Thx!
