### ISSUE TITLE
Can't parseDex

### ISSUE THREAD

**Issue by neervanbiqs** [libxposed/api#33]
```java
JarFile containerJar = new JarFile(mPkgParam.getApplicationInfo().sourceDir);
ZipEntry ze = containerJar.getEntry("classes.dex");
if (ze != null) {
   InputStream in = containerJar.getInputStream(ze);
   DexParser dp =  parseDex(ByteBuffer.wrap(in.readAllBytes()), true);
   ...
}
```

```java
java.io.IOException: Invalid dex file
    at Z.<init>(Unknown Source:330)
    at N.parseDex(Unknown Source:2)
    at io.github.libxposed.api.XposedInterfaceWrapper.parseDex(Unknown Source:2)
```

**Comment by JasonKhew96** [comment]
upstream problem, it's fixed in the internal version of LSPosed

**Comment by neervanbiqs** [comment]
Any news when will be available the new version with this fix?

**Comment by vvb2060** [comment]
https://t.me/LSPosedArchives/4153

**Comment by neervanbiqs** [comment]
> upstream problem, it's fixed in the internal version of LSPosed
Sorry, but I didn't understand. Where can I download the internal version with this fix?
> https://t.me/LSPosedArchives/4153
I downloaded the latest 1.9.2-7058 ver but it didn't help
