### ISSUE TITLE
API建议

### ISSUE THREAD

**Issue by yfw123** [libxposed/api#4]
参数可以支持json、protobuf等类型的直接转换么？

**Comment by yujincheng08** [comment]
这跟 xposed 有什么关系？

**Comment by yfw123** [comment]
> 这跟 xposed 有什么关系？

hook的方法类型为json、protobuf时xp不能直接转换。

**Comment by yujincheng08** [comment]
这是 xp 应该处理的问题？

**Comment by yfw123** [comment]
> 这是 xp 应该处理的问题？

ok
