### ISSUE TITLE
新API请求

### ISSUE THREAD

**Issue by EarzuChan** [libxposed/api#9]
请问能否做到在应用程序的类载入前回调？
我想载入自己的同名类来替换目标程序的类（先加载我的，使得ClassLoader就不再加载它的）

**Comment by yujincheng08** [comment]
这会严重影响性能，所以不会做。

**Comment by EarzuChan** [comment]
> 这会严重影响性能，所以不会做。

请问还有什么办法实现预加载类吗？Hook Application的onCreate也许还不算晚吧？但不能通杀，例如想替换com.android.material.*就可能不行。
